- name: Play 1 Create the Demo Tenant
  hosts: all
  gather_facts: no
######

  tasks:

    - set_fact:
        aci_login: &aci_login
          host: "{{ inventory_hostname }}"
          username: "wsuserX"
          password: "XXXXXXXX"
          use_ssl: yes
          validate_certs: no

######### Tenant Config ##########
    - name: Set {{ tenant_name }} Tenant
      aci_tenant:
        <<: *aci_login
        tenant: "testworkshop"
        state: present
      register: qResult 
      delegate_to: localhost